-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-05-01 17:55:36 CEST 
--   Modified   09.05
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



--ALTER TABLE users ALTER COLUMN password TYPE varchar(64);

CREATE TABLE Addresses
  (
    addressID SERIAL NOT NULL ,
    city      VARCHAR (50) ,
    country   VARCHAR (50) ,
    street    VARCHAR (50)
  ) ;
ALTER TABLE Addresses ADD CONSTRAINT Addresses_PK PRIMARY KEY ( addressID ) ;


CREATE TABLE Attraction
  (
    attractionID SERIAL NOT NULL ,
    name         VARCHAR (20) NOT NULL ,
    type         VARCHAR (20) NOT NULL
  ) ;
ALTER TABLE Attraction ADD CONSTRAINT Attraction_PK PRIMARY KEY ( attractionID ) ;


CREATE TABLE BoughtItem
  (
    boughtItemID          SERIAL NOT NULL ,
    ItemPrice_itemPriceID INTEGER NOT NULL ,
    CardUsage_useID       INTEGER NOT NULL
  ) ;
ALTER TABLE BoughtItem ADD CONSTRAINT BoughtItem_PK PRIMARY KEY ( boughtItemID ) ;


CREATE TABLE CardUsage
  (
    useDate      TIMESTAMP(0) NOT NULL ,
    useID        SERIAL NOT NULL ,
    Cards_cardID INTEGER NOT NULL,
    Terminal_terminalID INTEGER NOT NULL
  ) ;
ALTER TABLE CardUsage ADD CONSTRAINT CardUsage_PK PRIMARY KEY ( useID ) ;


CREATE TABLE Cards
  (
    cardID           SERIAL NOT NULL ,
    actDate          TIMESTAMP(0) ,
    expDate          TIMESTAMP(0) ,
    points           INTEGER ,
    Clients_clientID INTEGER NOT NULL
  ) ;
ALTER TABLE Cards ADD CONSTRAINT Cards_PK PRIMARY KEY ( cardID ) ;


CREATE TABLE Charges
  (
    chargeID         SERIAL NOT NULL ,
    chargeDate       TIMESTAMP(0) ,
    points           INTEGER ,
    Clients_clientID INTEGER NOT NULL
  ) ;
ALTER TABLE Charges ADD CONSTRAINT Charges_PK PRIMARY KEY ( chargeID ) ;


CREATE TABLE Clients
  (
    clientID         SERIAL NOT NULL ,
    registrationDate TIMESTAMP(0) ,
    Users_userID     INTEGER NOT NULL,
    points 	     INTEGER
  ) ;
ALTER TABLE Clients ADD CONSTRAINT Clients_PK PRIMARY KEY ( clientID ) ;


CREATE TABLE Employees
  (
    employeeID   SERIAL NOT NULL ,
    role         VARCHAR (30) ,
    Users_userID INTEGER NOT NULL
  ) ;
ALTER TABLE Employees ADD CONSTRAINT Employees_PK PRIMARY KEY ( employeeID ) ;


CREATE TABLE ItemPrice
  (
    itemPriceID           SERIAL NOT NULL ,
    price                 INTEGER NOT NULL ,
    Product_productID     INTEGER NOT NULL ,
    PriceList_priceListID INTEGER NOT NULL
  ) ;
ALTER TABLE ItemPrice ADD CONSTRAINT ItemPrice_PK PRIMARY KEY ( itemPriceID ) ;


CREATE TABLE PriceList
  (
    priceListID SERIAL NOT NULL ,
    startDate   TIMESTAMP(0) NOT NULL ,
    endDate     TIMESTAMP(0) NOT NULL
  ) ;
ALTER TABLE PriceList ADD CONSTRAINT PriceList_PK PRIMARY KEY ( priceListID ) ;


CREATE TABLE Product
  (
    productID SERIAL NOT NULL ,
    name      VARCHAR (20) NOT NULL
  ) ;
ALTER TABLE Product ADD CONSTRAINT Product_PK PRIMARY KEY ( productID ) ;


CREATE TABLE ProductItem
  (
    productItemID       SERIAL NOT NULL ,
    Terminal_terminalID INTEGER NOT NULL ,
    Product_productID   INTEGER NOT NULL
  ) ;
ALTER TABLE ProductItem ADD CONSTRAINT ProductItem_PK PRIMARY KEY ( productItemID ) ;


CREATE TABLE Terminal
  (
    terminalID              SERIAL NOT NULL ,
    lockTIme                INTEGER ,
    Attraction_attractionID INTEGER NOT NULL
  ) ;
ALTER TABLE Terminal ADD CONSTRAINT Terminal_PK PRIMARY KEY ( terminalID ) ;


CREATE TABLE Transactions
  (
    transactionID   SERIAL NOT NULL ,
    transactionDate TIMESTAMP(0) ,
    points          INTEGER ,
    Cards_cardID    INTEGER NOT NULL
  ) ;
ALTER TABLE Transactions ADD CONSTRAINT Transactions_PK PRIMARY KEY ( transactionID ) ;


CREATE TABLE Users
  (
    userID              SERIAL NOT NULL ,
    login               VARCHAR (20) NOT NULL ,
    password            VARCHAR (64) NOT NULL ,
    name                VARCHAR (50) NOT NULL ,
    surName             VARCHAR (50) NOT NULL ,
    documentNumber      VARCHAR (30) NOT NULL ,
    active              BOOLEAN NOT NULL DEFAULT TRUE ,
    Addresses_addressID INTEGER
  ) ;
ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY ( userID ) ;


ALTER TABLE BoughtItem ADD CONSTRAINT BoughtItem_CardUsage_FK FOREIGN KEY ( CardUsage_useID ) REFERENCES CardUsage ( useID ) ;

ALTER TABLE BoughtItem ADD CONSTRAINT BoughtItem_ItemPrice_FK FOREIGN KEY ( ItemPrice_itemPriceID ) REFERENCES ItemPrice ( itemPriceID ) ;

ALTER TABLE CardUsage ADD CONSTRAINT CardUsage_Cards_FK FOREIGN KEY ( Cards_cardID ) REFERENCES Cards ( cardID ) ;

ALTER TABLE CardUsage ADD CONSTRAINT CardUsage_Terminal_FK FOREIGN KEY ( Terminal_terminalID ) REFERENCES Terminal ( terminalID ) ;

ALTER TABLE Cards ADD CONSTRAINT Cards_Clients_FK FOREIGN KEY ( Clients_clientID ) REFERENCES Clients ( clientID ) ;

ALTER TABLE Charges ADD CONSTRAINT Charges_Clients_FK FOREIGN KEY ( Clients_clientID ) REFERENCES Clients ( clientID ) ;

ALTER TABLE Clients ADD CONSTRAINT Clients_Users_FK FOREIGN KEY ( Users_userID ) REFERENCES Users ( userID ) ;

ALTER TABLE Employees ADD CONSTRAINT Employees_Users_FK FOREIGN KEY ( Users_userID ) REFERENCES Users ( userID ) ;

ALTER TABLE ItemPrice ADD CONSTRAINT ItemPrice_PriceList_FK FOREIGN KEY ( PriceList_priceListID ) REFERENCES PriceList ( priceListID ) ;

ALTER TABLE ItemPrice ADD CONSTRAINT ItemPrice_Product_FK FOREIGN KEY ( Product_productID ) REFERENCES Product ( productID ) ;

ALTER TABLE ProductItem ADD CONSTRAINT ProductItem_Product_FK FOREIGN KEY ( Product_productID ) REFERENCES Product ( productID ) ;

ALTER TABLE ProductItem ADD CONSTRAINT ProductItem_Terminal_FK FOREIGN KEY ( Terminal_terminalID ) REFERENCES Terminal ( terminalID ) ;

ALTER TABLE Terminal ADD CONSTRAINT Terminal_Attraction_FK FOREIGN KEY ( Attraction_attractionID ) REFERENCES Attraction ( attractionID ) ;

ALTER TABLE Transactions ADD CONSTRAINT Transactions_Cards_FK FOREIGN KEY ( Cards_cardID ) REFERENCES Cards ( cardID ) ;

ALTER TABLE Users ADD CONSTRAINT Users_Addresses_FK FOREIGN KEY ( Addresses_addressID ) REFERENCES Addresses ( addressID ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
