package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Addresses generated by hbm2java
 */
public class Addresses  implements java.io.Serializable {


     private int addressid;
     private String city;
     private String country;
     private String street;
     private Set userses = new HashSet(0);

    public Addresses() {
    }

	
    public Addresses(int addressid) {
        this.addressid = addressid;
    }
    public Addresses(int addressid, String city, String country, String street, Set userses) {
       this.addressid = addressid;
       this.city = city;
       this.country = country;
       this.street = street;
       this.userses = userses;
    }
   
    public int getAddressid() {
        return this.addressid;
    }
    
    public void setAddressid(int addressid) {
        this.addressid = addressid;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


