package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Attraction generated by hbm2java
 */
public class Attraction  implements java.io.Serializable {


     private int attractionid;
     private String name;
     private String type;
     private Set terminals = new HashSet(0);

    public Attraction() {
    }

	
    public Attraction(int attractionid, String name, String type) {
        this.attractionid = attractionid;
        this.name = name;
        this.type = type;
    }
    public Attraction(int attractionid, String name, String type, Set terminals) {
       this.attractionid = attractionid;
       this.name = name;
       this.type = type;
       this.terminals = terminals;
    }
   
    public int getAttractionid() {
        return this.attractionid;
    }
    
    public void setAttractionid(int attractionid) {
        this.attractionid = attractionid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getTerminals() {
        return this.terminals;
    }
    
    public void setTerminals(Set terminals) {
        this.terminals = terminals;
    }




}


