package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1



/**
 * Boughtitem generated by hbm2java
 */
public class Boughtitem  implements java.io.Serializable {


     private int boughtitemid;
     private Cardusage cardusage;
     private Itemprice itemprice;

    public Boughtitem() {
    }

    public Boughtitem(int boughtitemid, Cardusage cardusage, Itemprice itemprice) {
       this.boughtitemid = boughtitemid;
       this.cardusage = cardusage;
       this.itemprice = itemprice;
    }
   
    public int getBoughtitemid() {
        return this.boughtitemid;
    }
    
    public void setBoughtitemid(int boughtitemid) {
        this.boughtitemid = boughtitemid;
    }
    public Cardusage getCardusage() {
        return this.cardusage;
    }
    
    public void setCardusage(Cardusage cardusage) {
        this.cardusage = cardusage;
    }
    public Itemprice getItemprice() {
        return this.itemprice;
    }
    
    public void setItemprice(Itemprice itemprice) {
        this.itemprice = itemprice;
    }




}


