package DBClasses;
// Generated 2016-05-09 22:48:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cardusage generated by hbm2java
 */
public class Cardusage  implements java.io.Serializable {


     private int useid;
     private Cards cards;
     private Terminal terminal;
     private Date usedate;
     private Set boughtitems = new HashSet(0);

    public Cardusage() {
    }

	
    public Cardusage(Cards cards, Date usedate) {
        this.cards = cards;
        this.usedate = usedate;
    }
    public Cardusage(Cards cards, Terminal terminal, Date usedate, Set terminals, Set boughtitems) {
       this.cards = cards;
       this.usedate = usedate;
       this.boughtitems = boughtitems;
       this.terminal = terminal;
    }
   
    public int getUseid() {
        return this.useid;
    }
    
    public void setUseid(int useid) {
        this.useid = useid;
    }
    public Cards getCards() {
        return this.cards;
    }
    
    public void setCards(Cards cards) {
        this.cards = cards;
    }
    public Date getUsedate() {
        return this.usedate;
    }
    
    public void setUsedate(Date usedate) {
        this.usedate = usedate;
    }
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }
    public Set getBoughtitems() {
        return this.boughtitems;
    }
    
    public void setBoughtitems(Set boughtitems) {
        this.boughtitems = boughtitems;
    }




}


