package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Charges generated by hbm2java
 */
public class Charges  implements java.io.Serializable {


     private int chargeid;
     private Clients clients;
     private Date chargedate;
     private Integer points;

    public Charges() {
    }

	
    public Charges(int chargeid, Clients clients) {
        this.chargeid = chargeid;
        this.clients = clients;
    }
    public Charges(int chargeid, Clients clients, Date chargedate, Integer points) {
       this.chargeid = chargeid;
       this.clients = clients;
       this.chargedate = chargedate;
       this.points = points;
    }
   
    public int getChargeid() {
        return this.chargeid;
    }
    
    public void setChargeid(int chargeid) {
        this.chargeid = chargeid;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Date getChargedate() {
        return this.chargedate;
    }
    
    public void setChargedate(Date chargedate) {
        this.chargedate = chargedate;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }




}


