package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int employeeid;
     private Users users;
     private String role;

    public Employees() {
    }

	
    public Employees(int employeeid, Users users) {
        this.employeeid = employeeid;
        this.users = users;
    }
    public Employees(int employeeid, Users users, String role) {
       this.employeeid = employeeid;
       this.users = users;
       this.role = role;
    }
   
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


