package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pricelist generated by hbm2java
 */
public class Pricelist  implements java.io.Serializable {


     private int pricelistid;
     private Date startdate;
     private Date enddate;
     private Set itemprices = new HashSet(0);

    public Pricelist() {
    }

	
    public Pricelist(int pricelistid, Date startdate, Date enddate) {
        this.pricelistid = pricelistid;
        this.startdate = startdate;
        this.enddate = enddate;
    }
    public Pricelist(int pricelistid, Date startdate, Date enddate, Set itemprices) {
       this.pricelistid = pricelistid;
       this.startdate = startdate;
       this.enddate = enddate;
       this.itemprices = itemprices;
    }
   
    public int getPricelistid() {
        return this.pricelistid;
    }
    
    public void setPricelistid(int pricelistid) {
        this.pricelistid = pricelistid;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Set getItemprices() {
        return this.itemprices;
    }
    
    public void setItemprices(Set itemprices) {
        this.itemprices = itemprices;
    }




}


