package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int productid;
     private String name;
     private Set productitems = new HashSet(0);
     private Set itemprices = new HashSet(0);

    public Product() {
    }

	
    public Product(int productid, String name) {
        this.productid = productid;
        this.name = name;
    }
    public Product(int productid, String name, Set productitems, Set itemprices) {
       this.productid = productid;
       this.name = name;
       this.productitems = productitems;
       this.itemprices = itemprices;
    }
   
    public int getProductid() {
        return this.productid;
    }
    
    public void setProductid(int productid) {
        this.productid = productid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductitems() {
        return this.productitems;
    }
    
    public void setProductitems(Set productitems) {
        this.productitems = productitems;
    }
    public Set getItemprices() {
        return this.itemprices;
    }
    
    public void setItemprices(Set itemprices) {
        this.itemprices = itemprices;
    }




}


