package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1



/**
 * Productitem generated by hbm2java
 */
public class Productitem  implements java.io.Serializable {

     private int productitemid;
     private Product product;
     private Terminal terminal;

    public Productitem() {
    }

    public Productitem(int productitemid, Product product, Terminal terminal) {
       this.productitemid = productitemid;
       this.product = product;
       this.terminal = terminal;
    }
   
    public int getProductitemid() {
        return this.productitemid;
    }
    
    public void setProductitemid(int productitemid) {
        this.productitemid = productitemid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }




}


