package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private int transactionid;
     private Cards cards;
     private Date transactiondate;
     private Integer points;

    public Transactions() {
    }

	
    public Transactions(int transactionid, Cards cards) {
        this.transactionid = transactionid;
        this.cards = cards;
    }
    public Transactions(int transactionid, Cards cards, Date transactiondate, Integer points) {
       this.transactionid = transactionid;
       this.cards = cards;
       this.transactiondate = transactiondate;
       this.points = points;
    }
   
    public int getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(int transactionid) {
        this.transactionid = transactionid;
    }
    public Cards getCards() {
        return this.cards;
    }
    
    public void setCards(Cards cards) {
        this.cards = cards;
    }
    public Date getTransactiondate() {
        return this.transactiondate;
    }
    
    public void setTransactiondate(Date transactiondate) {
        this.transactiondate = transactiondate;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }




}


