package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userid;
     private Addresses addresses;
     private String login;
     private String password;
     private String name;
     private String surname;
     private String documentnumber;
     private Boolean active;
     private Set employeeses = new HashSet(0);
     private Set clientses = new HashSet(0);

    public Users() {
    }

	
    public Users(int userid, Addresses addresses, String login, String password, String name, String surname, String documentnumber) {
        this.userid = userid;
        this.addresses = addresses;
        this.login = login;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.documentnumber = documentnumber;
        this.active = active;
    }
    public Users(int userid, Addresses addresses, String login, String password, String name, String surname, String documentnumber, Boolean active, Set employeeses, Set clientses) {
       this.userid = userid;
       this.addresses = addresses;
       this.login = login;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.documentnumber = documentnumber;
       this.active = active;
       this.employeeses = employeeses;
       this.clientses = clientses;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public Addresses getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Addresses addresses) {
        this.addresses = addresses;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getDocumentnumber() {
        return this.documentnumber;
    }
    
    public void setDocumentnumber(String documentnumber) {
        this.documentnumber = documentnumber;
    }
    
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active){
        this.active = active;
    }
    
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }
    public Set getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set clientses) {
        this.clientses = clientses;
    }




}


